language: bash

env:
  - SHUNIT_COLOR='always'

script:
  # Execute the unit tests.
  - ./test_runner

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - ksh
      - zsh

matrix:
  include:
    - os: linux
      script:
        # Run the source through ShellCheck (http://www.shellcheck.net).
        #- shellcheck -s sh log4sh log4sh_*

branches:
  only:
  - master
  # Tags, e.g. v2.1.8
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
