#! /bin/sh
# $Id$

myName=`basename $0`

SHELLS='/bin/sh /bin/bash /bin/dash /bin/ksh /bin/pdksh'

[ $# -ne 0 ] && shells=$@ || shells=${SHELLS}

cat <<EOF
#------------------------------------------------------------------------------
# System data
#

EOF

# output system data
echo "$ date"
date

echo "$ uname -a"
uname -a

echo
for shell in ${shells}; do
  # check for existance of shell
  if [ ! -x ${shell} ]; then
    echo "${myName}:WARN unable to run tests with the ${shell} shell"
    continue
  fi

  # see if shell is a sym-link
  if [ -h ${shell} ]; then
    echo "${myName}:WARN the ${shell} shell is a sym-link; ignoring"
    continue
  fi

  cat <<EOF

#------------------------------------------------------------------------------
# Running the test suite with ${shell}
#
EOF

  case `basename ${shell}` in
    bash) echo; ${shell} --version; ;;
    dash) ;;
    ksh)
      version=`${shell} --version 2>&1`
      exitVal=$?
      if [ ${exitVal} -eq 2 ]; then
        echo
        echo "${version}"
      fi
      ;;
    pdksh) ;;
    zsh) ;;
  esac

  for suite in test[A-Z]*; do
    if [ -x ${suite} ]; then
      # execute the test
      suiteName=`expr "${suite}" : 'test\(.*\)'`
      echo
      echo "--- Executing the '${suiteName}' test suite ---" >&2
      ( exec ${shell} ./${suite} )
    fi
  done
done
