#! /bin/sh
# $Id$

MY_NAME=`basename $0`
MY_PATH=`dirname $0`

# load common unit test functions
. "${MY_PATH}/test-functions.inc"

#------------------------------------------------------------------------------
# suite tests
#

testAsciiCharset()
{
  # save stdin and redirect it from an in-line file
  exec 9<&0 <<EOF
# 20-2F (escaping the leading space)
\ !"#$%&'()*+,-./
# 30-3F
0123456789:;<=>?
# 40-4F
@ABCDEFGHIJKLMNO
# 50-5F (escaping the backslash)
PQRSTUVWXYZ[\\]^_
# 60-6F
\`abcdefghijklmno
# 70-7E (7F is the unprintable DEL char)
pqrstuvwxzy{|}~
EOF
  while read expected; do
    # ignore comment lines or blank lines
    echo "${expected}" |egrep -v '^(#|$)' >/dev/null || continue

    # test the function
    actual="`logger_info \"${expected}\"`"
    ${DEBUG} "expected='${expected}' actual='${actual}'"
    assertEquals "'${expected}' != '${actual}'" "${expected}" "${actual}"
  done
  # restore stdin
  exec 0<&9 9<&-
}

#------------------------------------------------------------------------------
# suite functions
#

oneTimeSetUp()
{
  # source log4sh
  ${DEBUG} 'loading log4sh'
  LOG4SH_CONFIGURATION="${MY_NAME}.log4sh" . ./log4sh
}

#------------------------------------------------------------------------------
# main
#

# load and run shUnit2
${DEBUG} 'loading shUnit2'
. ./shunit2
