#! /bin/sh
# $Id: test-log4sh,v 1.7 2004/06/21 22:58:52 kward Exp $
#
# Author: Kate Ward <kate.ward@forestent.com>
#
# The spiffy comments were shamelessly pulled from the lf5 examples from log4j.
#

# load log4sh
if [ -r log4sh ]; then
   . log4sh
else
   echo "error: could not load (log4sh)"
   exit 1
fi

# a sample file to log to
logFile_simple=log4sh-simple.log
logFile_pattern=log4sh-pattern.log

# setup the initial appenders
logger_setLevel INFO
logger_addAppender $logFile_simple Simple
appender_setAppend $logFile_simple false
appender_setLevel $logFile_simple DEBUG
logger_addAppender $logFile_pattern Pattern
#appender_setPattern $logFile_pattern "%d [%t] - %m"

logger_debug "Hello, my name is Homer Simpson."
logger_debug "Hello, my name is Lisa Simpson."
logger_debug "Hello, my name is Marge Simpson."
logger_debug "Hello, my name is Bart Simpson."
logger_debug "Hello, my name is Maggie Simpson."

appender_setLayout STDERR None
logger_info "We are the Simpsons!"
logger_info "Mmmmmm .... Chocolate."
logger_info "Homer likes chocolate"
logger_info "Doh!"
logger_info "We are the Simpsons!"

appender_setLayout STDERR Simple
logger_warn "Bart: I am through with working! Working is for chumps!\
 Homer: Son, I'm proud of you. I was twice your age before\
 I figured that out."
logger_warn "Mmm...forbidden donut."
logger_warn "D'oh! A deer! A female deer!"
logger_warn "Truly, yours is a butt that won't quit.\
 - Bart, writing as Woodrow to Ms. Krabappel."

appender_setLevel STDERR OFF
logger_error "Dear Baby, Welcome to Dumpsville. Population: you."
logger_error "Mr. Hutz, are you aware you're not wearing pants?"

appender_setLevel STDERR DEBUG
logger_fatal "Eep."
logger_fatal "Mmm...forbidden donut."
logger_fatal "D'oh! A deer! A female deer!"
logger_fatal "Mmmmmm .... Chocolate."

appender_setLayout STDERR Pattern
logger_info "test of the default pattern layout"

logger_setFilename `basename $0`
appender_setPattern STDERR '%d [%F] %p - %m%n'
logger_info "test of setting a pattern layout"

appender_setPattern STDERR '%d %p - %m%n'
logger_info "test of setting a pattern layout again"

appender_setPattern $logFile_simple '%d [%F] %p - %m'
logger_info "setting a pattern for a simple layout logger.  shouldn't matter"

appender_setPattern $logFile_pattern '%d [%f] %p - %m%n'
logger_info "setting a pattern for a patterned layout file logger, using an invalid character conversion."

appender_setPattern STDERR '%p [%t]: %m%n'
logger_info "setting a pattern layout that uses the thread name conversion character.  it isn't set yet, so it should be empty..."
logger_setThreadName `basename $0`
logger_info "the thread name is now set to the name of this script, so it should show up in output now"
